### ISSUE TITLE
Change paid app to a free app with in-app purchase 

### ISSUE THREAD

**Issue by VigneshPalanisamy** [crashoverride777/swifty-receipt-validator#4]
I had my app on the app store for 1.99USD and now changed it too a freemium app with and in-app purchase(Ad-Free Version) for 1.99USD.

How can I go about upgrading my existing customers (those who bought the app from the app store ) as an in-app purchaser(Ad-Free Version) on update?

Will your solution, solve my problem?

Thanks

**Comment by crashoverride777** [comment]
Hey,

Thanks for your question and checking out my helper.

You have 3 options basically.

1) Using receipt validation

Essentially you will have to read the receipt data as described in the instructions and check for a specific date/version or something and unlock the content if necessary. 

For example you can use the below key when reading the receipt.

    public enum SwiftyReceiptValidatorInfoKey: String {
           case original_application_version // The version of the app that was originally purchased. This corresponds to the value of CFBundleVersion (in iOS) or CFBundleShortVersionString (in OS X) in the Info.plist file when the purchase was originally made.
    
and than run a check to see if the version is lower/equal to the last version of your app that was paid. If it is unlock the content for the user.

This might be too complicated tho, especially if you haven't used receipt validation before. I haven't done it myself yet.

2) A easier but less reliable way

Update your paid app with some sort of system, e.g a bool property or something similar, that you set to true once a user purchased the old version. 

So for example create a property

     var didPurchasePaidApp = false

than when the app launches you can check the last version of the app that was paid (e.g v1.1)

       let currentVesion = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "-"
       if currentVesion <= 1.1 {
              didPurchasePaidApp = true
             // save property in user defaults or better keychain.
       }

and set the property to true. Than simply unlock the content for the user if is is set to true.


       if didPurchasePaidApp {

            /// unlock content
      }
       
NOTE:

Bear in mind you have to make sure your users upgrade to this version with the above check so your app saves their content. This might not be a guarantee because they could skip this version for some reason and than it will not work.

http://stackoverflow.com/questions/19390810/change-paid-app-to-free-but-know-if-user-previously-purchased-it

3) If you have a small user base you could also simply upgrade your app to the free version. Than send all your users that paid for the app a PromoCode for the in app purchase in the free version that unlocks the content. It is now very easy to create promo codes for in app purchases via iTunes connect.

Hope this helps

**Comment by VigneshPalanisamy** [comment]
Hi,
Thanks for your reply
In the third option, is there a way to find our paid user?

**Comment by VigneshPalanisamy** [comment]
We tried the first option but it does not work in the production mode.
We can't use the second option as some of our user may delete the app. so the user defaults also will be deleted.

**Comment by crashoverride777** [comment]
Hey,

Sorry about that, I haven't had an app yet that I changed from paid to free. 

What about using iCloud / keychain for option 2?. This way progress is saved even if app is uninstalled.

Not sure how you can handle option 3.

**Comment by VigneshPalanisamy** [comment]
Thanks,
        Finally i resolved by the first option Receipt validation i had added a check
```
/// Check receipt contains correct bundle and product id for app 
/// Or Check receipt contains correct bundle id for app and Original application version is paid version
            guard self.isAppBundleIDMatching(withReceipt: receipt) && (self.isPaidVersion(withReceipt: receipt) || self.isTransactionProductIDMatching(withReceipt: receipt)) else {
                requestFailHandler(handler)
                return
            }
```

**Comment by crashoverride777** [comment]
Hey,

Thanks so much for updating this. Thanks as well for your code sample, I will defiantly integrate this in a future update. Please keep me posted incase it doesn't work or you made a change.

Sorry I couldn't help you more since I haven't done this myself yet.
